### ISSUE TITLE
Change loc url to https 

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/bpldc_authority_api#13]
In the seeds task the LcVocabFetcher needs the the lc_url for loc to be changed to https. This is preventing basic_genres/resource_types/etc from getting seeded initally

**Comment by bbarberBPL** [comment]
Also ideally when you build the faarday object in the class it should be changed from 

`lc_response = Faraday.get(lc_url)`

To 
```
lc_response = Faraday.get(lc_url) do |f|
          f.use  FaradayMiddleware::FollowRedirects, limit: 3
          f.adapter Faraday.default_adapter
   end
```
You may have to add the 'faraday-middleware` gem in the gem file if its not there

**Comment by ebenenglish** [comment]
We should update the QA dependency to the latest version to fix this problem with id searches.

Was fixed upstream here:
https://github.com/samvera/questioning_authority/pull/321
